config/routes.rb
Rails.application.routes.draw do
  #   get 'posts/new'

  #   get 'users/top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top', to: 'users#top', as: :top
  root 'users#top'

  # 通常の指定
  #   get 'posts/new', to:'posts#new', as: :new_post

  get '/profile/edit', to: 'users#edit', as: :profile_edit

  post '/profile/edit', to: 'users#update'

  get '/profile/(:id)', to: 'users#show', as: :profile

  get '/follower_list/(:id)', to: 'users#follower_list', as: :follower_list

  get '/follow_list/(:id)', to: 'users#follow_list', as: :follow_list

  get '/sign_up', to: 'users#sign_up', as: :sign_up

  post '/sign_up', to: 'users#sign_up_process'

  get '/sign_in', to: 'users#sign_in', as: :sign_in

  post '/sign_in', to: 'users#sign_in_process'

  get '/sign_out', to: 'users#sign_out', as: :sign_out

  post '/profile/edit', to: 'users#update'
  
  # フォロー機能
  get '/follow/(:id)', to: 'users#follow', as: :follow
  

  # resourcesメソッドを使った指定
  resources :posts do
    member do
      # いいね
      get 'like', to: 'posts#like', as: :like
      # コメント投稿
      post 'comment', to: 'posts#comment', as: :comment
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  </head>

  <body class="logined">
    <header class="global_header">
      <!-- ロゴ -->
      <div class="icon">
      </div>
      <%= link_to top_path do %>
        <h1 class="logo" title="トップ">artshare</h1>
      <% end %>
      
      <!-- 検索フォーム -->
      <form class="search">
        <input type="text" placeholder="検索ワードを入力" name="word" value="">
      </form>
      <!-- メニュー -->
      <ul class="menu">
        <li>
          <!-- サインアウト -->
          <%= link_to sign_out_path do %>
            <i class="fa fa-sign-out" title="サインアウト"></i>
          <% end %>
        </li>
        <li>
          <!-- プロフィールページ -->
          <%= link_to profile_path(current_user) do %>  
            <i class="fa fa-user-o" title="プロフィール"></i>
          <% end %>
        </li>
        <li>
          <!-- 投稿 -->
          <%= link_to new_post_path do %>
            <i class="fa fa-upload" title="新規投稿"></i>
          <% end %>
        </li>
      </ul>
    </header>
    
    <% flash.each do |type, message| %>
    <div class="alert alert-<%= type %>"><%= message %></div>
    <% end %>
    
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
        window.setTimeout(function() {
            $(".alert").slideUp();
        }, 3000);
    </script>
  </body>
</html>

app/views/layouts/application_not_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
      window.setTimeout(function() {
        $(".alert").slideUp();
      }, 3000);
    </script>
  </body>
</html>